In [48]:
pip install pandas

Requirement already satisfied: pandas in c:\Users\HP\OneDrive\Desktop\PYTHON\venv\Lib\site-packages (3.1.0)
Requirement already satisfied: numpy>=2.0.2 in c:\Users\HP\OneDrive\Desktop\PYTHON\venv\Lib\site-packages (from pandas) (2.5.4)
Requirement already satisfied: python-dateutil>=2.9.0 in c:\Users\HP\OneDrive\Desktop\PYTHON\venv\Lib\site-packages (from pandas) (3.0.0)
Requirement already satisfied: tzdata in c:\Users\HP\OneDrive\Desktop\PYTHON\venv\Lib\site-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.6 in c:\Users\HP\OneDrive\Desktop\PYTHON\venv\Lib\site-packages (from python-dateutil>=2.9.0->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [49]:
import pandas as pd

In [50]:
import numpy as np

In [51]:
import seaborn as sns

In [52]:
df = sns.load_dataset('tips')

In [53]:
from sklearn.preprocessing import LabelEncoder
encoder_time = LabelEncoder()

encoded_data = encoder_time.fit_transform(df['time'])

In [54]:
print('classes',encoder_time.classes_)

classes ['Dinner' 'Lunch']

In [55]:
encoded_data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [56]:
for category , number in zip (encoder_time.classes_, range(len(encoder_time.classes_))):
    print(category,"-----------",number)

Dinner ----------- 0
Lunch ----------- 1

In [57]:
encoder_time = LabelEncoder()

encoder_data = encoder_time.fit_transform(df['day'])

In [58]:
from sklearn.preprocessing import OneHotEncoder

In [59]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [60]:
ohe = OneHotEncoder(sparse_output=False)

ohe.fit_transform(df[['sex','smoker']])

array([[1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.]])

In [61]:
ohe = OneHotEncoder(sparse_output=False, drop='first')

ohe_encoder=ohe.fit_transform(df[['sex','smoker']])
ohe_encoder

array([[0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [1., 0.],
       [1., 0.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [1., 0.],
       [0., 0.]])

In [62]:
df1=pd.DataFrame(ohe_encoder,columns=ohe.get_feature_names_out())

In [63]:
df1

     sex_Male  smoker_Yes
0         0.0         0.0
1         1.0         0.0
2         1.0         0.0
3         1.0         0.0
4         0.0         0.0
..        ...         ...
239       1.0         0.0
240       0.0         1.0
241       1.0         1.0
242       1.0         0.0
243       0.0         0.0

[244 rows x 2 columns]

In [64]:
pd.concat([df,df1],axis=1)

     total_bill   tip     sex smoker   day    time  size  sex_Male  smoker_Yes
0         16.99  1.01  Female     No   Sun  Dinner     2       0.0         0.0
1         10.34  1.66    Male     No   Sun  Dinner     3       1.0         0.0
2         21.01  3.50    Male     No   Sun  Dinner     3       1.0         0.0
3         23.68  3.31    Male     No   Sun  Dinner     2       1.0         0.0
4         24.59  3.61  Female     No   Sun  Dinner     4       0.0         0.0
..          ...   ...     ...    ...   ...     ...   ...       ...         ...
239       29.03  5.92    Male     No   Sat  Dinner     3       1.0         0.0
240       27.18  2.00  Female    Yes   Sat  Dinner     2       0.0         1.0
241       22.67  2.00    Male    Yes   Sat  Dinner     2       1.0         1.0
242       17.82  1.75    Male     No   Sat  Dinner     2       1.0         0.0
243       18.78  3.00  Female     No  Thur  Dinner     2       0.0         0.0

[244 rows x 9 columns]

In [65]:
from sklearn.preprocessing import FunctionTransformer
import pandas as pd

In [66]:
power = FunctionTransformer(np.log10)
power.fit_transform(df['tip'])

0      0.004321
1      0.220108
2      0.544068
3      0.519828
4      0.557507
         ...
239    0.772322
240    0.301030
241    0.301030
242    0.243038
243    0.477121
Name: tip, Length: 244, dtype: float64

In [67]:
log1 = FunctionTransformer(np.log10)
log1.fit_transform(df['tip'])

0      0.004321
1      0.220108
2      0.544068
3      0.519828
4      0.557507
         ...
239    0.772322
240    0.301030
241    0.301030
242    0.243038
243    0.477121
Name: tip, Length: 244, dtype: float64

In [68]:
log_2 = FunctionTransformer(np.log10)
log_2.fit_transform(df['tip'])

0      0.004321
1      0.220108
2      0.544068
3      0.519828
4      0.557507
         ...
239    0.772322
240    0.301030
241    0.301030
242    0.243038
243    0.477121
Name: tip, Length: 244, dtype: float64

In [69]:
import numpy as np
from sklearn.preprocessing import PowerTransformer

In [70]:
# A right-skewed features

X = np.array([[-1],[0],[5],[5],[10],[900]])

# Create the transformer

pt = PowerTransformer(method="yeo-johnson")

# fit and transformer

X_tansformed = pt.fit_transform(X)

print("Original:")
print(X.ravel())

print("\nTransformed:")
print(np.round(X_tansformed.ravel(),3))

print("\nLearned lambda:")
print(pt.lambdas_)

Original:
[ -1   0   5   5  10 900]

Transformed:
[-1.562 -0.729  0.117  0.117  0.364  1.694]

Learned lambda:
[-0.12362091]

In [71]:
# A right-skewed features

y = np.array([[1],[4],[3],[5],[10],[50]])

# Create the transformer

pt = PowerTransformer(method="box-cox")

# fit and transformer

y_tansformed = pt.fit_transform(y)

print("Original:")
print(y.ravel())

print("\nTransformed:")
print(np.round(y_tansformed.ravel(),3))

print("\nLearned lambda:")
print(pt.lambdas_)

Original:
[ 1  4  3  5 10 50]

Transformed:
[-1.635 -0.18  -0.451  0.02   0.59   1.656]

Learned lambda:
[-0.19159336]

In [72]:
import numpy as np
import pandas as pd

# Creating sample data
data = {
    "CustomerID": [101, 102, 103, 104, 105, 106, 107, 108],
    # --- Numerical Columns with Nulls ---
    "Age": [25, np.nan, 35, 45, np.nan, 29, 41, 38],
    "Salary": [50000, 64000, np.nan, 82000, 58000, np.nan, 95000, 72000],
    "Experience_Years": [2, 5, 8, np.nan, 4, 3, 12, np.nan],
    # --- Categorical Columns with Nulls ---
    "Department": [
        "IT",
        "HR",
        np.nan,
        "Finance",
        "IT",
        "Marketing",
        np.nan,
        "HR",
    ],
    "City": [
        "New York",
        "London",
        "Paris",
        np.nan,
        "London",
        np.nan,
        "Berlin",
        "Paris",
    ],
    "Purchased": ["Yes", "No", "No", "Yes", np.nan, "Yes", "No", "Yes"],
}

df = pd.DataFrame(data)
display(df)

   CustomerID   Age   Salary  Experience_Years Department      City Purchased
0         101  25.0  50000.0               2.0         IT  New York       Yes
1         102   NaN  64000.0               5.0         HR    London        No
2         103  35.0      NaN               8.0        NaN     Paris        No
3         104  45.0  82000.0               NaN    Finance       NaN       Yes
4         105   NaN  58000.0               4.0         IT    London       NaN
5         106  29.0      NaN               3.0  Marketing       NaN       Yes
6         107  41.0  95000.0              12.0        NaN    Berlin        No
7         108  38.0  72000.0               NaN         HR     Paris       Yes

In [73]:
df.head()

   CustomerID   Age   Salary  Experience_Years Department      City Purchased
0         101  25.0  50000.0               2.0         IT  New York       Yes
1         102   NaN  64000.0               5.0         HR    London        No
2         103  35.0      NaN               8.0        NaN     Paris        No
3         104  45.0  82000.0               NaN    Finance       NaN       Yes
4         105   NaN  58000.0               4.0         IT    London       NaN

In [74]:
from sklearn.impute import SimpleImputer

*FOR MEAN*

In [75]:
from sklearn.impute import SimpleImputer

In [76]:
imputer = SimpleImputer(strategy='mean')
imputer.fit_transform(df[['Salary']])

array([[50000.        ],
       [64000.        ],
       [70166.66666667],
       [82000.        ],
       [58000.        ],
       [70166.66666667],
       [95000.        ],
       [72000.        ]])

In [77]:
imputer = SimpleImputer(strategy='mean')
imputer.fit_transform(df[['Salary']])

array([[50000.        ],
       [64000.        ],
       [70166.66666667],
       [82000.        ],
       [58000.        ],
       [70166.66666667],
       [95000.        ],
       [72000.        ]])

In [78]:
imputer = SimpleImputer(strategy='mean')
imputer.fit_transform(df[['Salary']])

array([[50000.        ],
       [64000.        ],
       [70166.66666667],
       [82000.        ],
       [58000.        ],
       [70166.66666667],
       [95000.        ],
       [72000.        ]])

In [79]:
imputer = SimpleImputer(strategy='mean')
imputer.fit_transform(df[['Salary']]).flatten()

array([50000.        , 64000.        , 70166.66666667, 82000.        ,
       58000.        , 70166.66666667, 95000.        , 72000.        ])

In [80]:
imputer = SimpleImputer(strategy='mean')
df['new_salary']=imputer.fit_transform(df[['Salary']]).flatten()

In [81]:
df

,CustomerID,Age,Salary,Experience_Years,Department,City,Purchased,new_salary
0,101,25.0,50000.0,2.0,IT,New York,Yes,50000.000000
1,102,NaN,64000.0,5.0,HR,London,No,64000.000000
2,103,35.0,NaN,8.0,NaN,Paris,No,70166.666667
3,104,45.0,82000.0,NaN,Finance,NaN,Yes,82000.000000
4,105,NaN,58000.0,4.0,IT,London,NaN,58000.000000
5,106,29.0,NaN,3.0,Marketing,NaN,Yes,70166.666667
6,107,41.0,95000.0,12.0,NaN,Berlin,No,95000.000000
7,108,38.0,72000.0,NaN,HR,Paris,Yes,72000.000000

*FOR MEDIAN*

In [82]:
imputer = SimpleImputer(strategy='median')
imputer.fit_transform(df[['Experience_Years']])

array([[ 2. ],
       [ 5. ],
       [ 8. ],
       [ 4.5],
       [ 4. ],
       [ 3. ],
       [12. ],
       [ 4.5]])

In [83]:
imputer = SimpleImputer(strategy='median')
df=imputer.fit_transform(df[['Experience_Years']]).flatten()

In [84]:
df

array([ 2. ,  5. ,  8. ,  4.5,  4. ,  3. , 12. ,  4.5])

*MODE*

In [87]:
import numpy as np
import pandas as pd

# Creating sample data
data = {
    "CustomerID": [101, 102, 103, 104, 105, 106, 107, 108],
    # --- Numerical Columns with Nulls ---
    "Age": [25, np.nan, 35, 45, np.nan, 29, 41, 38],
    "Salary": [50000, 64000, np.nan, 82000, 58000, np.nan, 95000, 72000],
    "Experience_Years": [2, 5, 8, np.nan, 4, 3, 12, np.nan],
    # --- Categorical Columns with Nulls ---
    "Department": [
        "IT",
        "HR",
        np.nan,
        "Finance",
        "IT",
        "Marketing",
        np.nan,
        "HR",
    ],
    "City": [
        "New York",
        "London",
        "Paris",
        np.nan,
        "London",
        np.nan,
        "Berlin",
        "Paris",
    ],
    "Purchased": ["Yes", "No", "No", "Yes", np.nan, "Yes", "No", "Yes"],
}

df = pd.DataFrame(data)
display(df)

   CustomerID   Age   Salary  Experience_Years Department      City Purchased
0         101  25.0  50000.0               2.0         IT  New York       Yes
1         102   NaN  64000.0               5.0         HR    London        No
2         103  35.0      NaN               8.0        NaN     Paris        No
3         104  45.0  82000.0               NaN    Finance       NaN       Yes
4         105   NaN  58000.0               4.0         IT    London       NaN
5         106  29.0      NaN               3.0  Marketing       NaN       Yes
6         107  41.0  95000.0              12.0        NaN    Berlin        No
7         108  38.0  72000.0               NaN         HR     Paris       Yes

In [88]:
imputer = SimpleImputer(strategy='most_frequent')
df['City']=imputer.fit_transform(df[['City']]).flatten()

In [89]:
df

   CustomerID   Age   Salary  Experience_Years Department      City Purchased
0         101  25.0  50000.0               2.0         IT  New York       Yes
1         102   NaN  64000.0               5.0         HR    London        No
2         103  35.0      NaN               8.0        NaN     Paris        No
3         104  45.0  82000.0               NaN    Finance    London       Yes
4         105   NaN  58000.0               4.0         IT    London       NaN
5         106  29.0      NaN               3.0  Marketing    London       Yes
6         107  41.0  95000.0              12.0        NaN    Berlin        No
7         108  38.0  72000.0               NaN         HR     Paris       Yes